PREP(canRearm);
PREP(canRearmFromOutside);
PREP(distanceSelection);
PREP(getAvailableAmmoItems)
PREP(getMagazineMaxAmmo);
PREP(getMagazineName);
PREP(getRefillAmmoItems);
PREP(rearm);
PREP(rearmProgress);
PREP(simulateRearmEvents);
PREP(sortAvailableAmmoItems);
