name = "PzGrenBtl 402"
prefix = "PzGrenBtl402"
author = "PzGrenBtl 402"
template = "cba"
mainprefix = "z"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "PzGrenBtl402_Logo.paa",
    "meta.cpp"
]
folder_optionals = false

modname = "PzGrenBtl402"
key_name = "PzGrenBtl402_{{version}}"
authority = "PzGrenBtl402_{{version}}-{{git \"id 8\"}}"

prebuild = ["!compile_sqf"]
postbuild = ["!compile_sqf_cleanup"]
releasebuild = [
    "@zip PzGrenBtl402_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# SQF Compilation
[scripts.compile_sqf]
steps_windows = [
    "echo Compile SQF",
    "powershell -Command if (Get-Command python -ErrorAction SilentlyContinue) {python tools/compile_sqf.py cleanup build} else {echo 'Python not found, skipping SQF compilation'}"
]
only_release = true
show_output = true

[scripts.compile_sqf_cleanup]
steps_windows = [
    "echo Compile SQF Cleanup",
    "powershell -Command if (Get-Command python -ErrorAction SilentlyContinue) {python tools/compile_sqf.py cleanup} else {echo 'Python not found, skipping SQFC cleanup'}"
]
only_release = true
show_output = true
