
#define MAINPREFIX z
#define PREFIX PzGrenBtl402

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIREDVERSION 2.02
#define REQUIRED_CBA_VERSION {3,15,5}
#define REQUIRED_ACE_VERSION {3,13,6}

#ifdef COMPONENT_BEAUTIFIED
  #define COMPONENT_NAME QUOTE(PzGrenBtl402 - COMPONENT_BEAUTIFIED)
#else
  #define COMPONENT_NAME QUOTE(PzGrenBtl402 - COMPONENT)
#endif
